// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SidePanelSwitcher
{
    internal sealed partial class Vsix
    {
        public const string Id = "afa51053-b6d6-4095-9b48-c1a60e2b5cf8";
        public const string Name = "Switch Auto Hide Mode by Shortcut";
        public const string Description = @"Switch auto hide mode of left/right/bottom/top tool window groups by shortcut";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alisander Q";
        public const string Tags = "auto hide, tool window, panel, shortcut";
    }
}
