// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SidePanelSwitcher
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSidePanelSwitcherPackageString = "5f0aa1cb-a29e-49c7-909f-5ba187a48e2b";
        public static Guid guidSidePanelSwitcherPackage = new Guid(guidSidePanelSwitcherPackageString);

        public const string guidSidePanelSwitcherPackageCmdSetString = "49cc4a7b-a6f3-4298-816e-26883e792fb9";
        public static Guid guidSidePanelSwitcherPackageCmdSet = new Guid(guidSidePanelSwitcherPackageCmdSetString);

        public const string guidImagesString = "06187b4d-c60d-4175-9b38-b31310bed4bc";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidBottomPanelSwitchCommand = 0x1021;
        public const int cmdidRightPanelSwitchCommand = 0x1022;
        public const int cmdidTopPanelSwitchCommand = 0x1023;
        public const int cmdidLeftPanelSwitchCommand = 0x1024;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}